---
- name: Create a group and add users
  hosts: cockpit
  become: yes
  tasks:
    - name: Create group with specific GID
      ansible.builtin.group: #fqcn fully qualified collection name for managing group
        name: testgroup #group name
        gid: 2001 #group id
        state: present #create if not present
    - name: Add users to group
      ansible.builtin.user: #fqcn for managing user
        name: "{{ item }}"
        groups: testgroup
        append: yes
      loop:
        - testuser
        - anotheruser
