---
- name: Manage user passwords
  hosts: cockpit
  become: yes
  vars: #define users and their hashed password
    users:
      - username: testuser
        password: "{{ 'jx90dx97' | password_hash('sha512') }}"
      - username: anotheruser
        password: "{{ 'anotherpass' | password_hash('sha512') }}"
  tasks:
    - name: Update user passwords
      ansible.builtin.user: 
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        update_password: always
      loop: "{{ users }}"
